#!python
# emacs: -*- mode: python-mode; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
#
#   See COPYING file distributed along with the NiBabel package for the
#   copyright and license terms.
#
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
"""
Quick summary of the differences among a set of neuroimaging files
"""
from __future__ import division, print_function, absolute_import

import sys
from optparse import OptionParser, Option
from six import binary_type

import numpy as np

import json_tricks

import nibabel as nib
import nibabel.cmdline.utils
from nibabel.cmdline.utils import _err, verbose, table2string, ap, safe_get
import fileinput

__author__ = 'Yaroslav Halchenko & Christopher Cheng'
__copyright__ = 'Copyright (c) 2017 NiBabel contributors'
__license__ = 'MIT'


def get_opt_parser():
    # use module docstring for help output
    p = OptionParser(
        usage="%s [OPTIONS] [FILE ...]\n\n" % sys.argv[0] + __doc__,
        version="%prog " + nib.__version__)

    p.add_options([
        Option("-v", "--verbose", action="count",
               dest="verbose", default=0,
               help="Make more noise.  Could be specified multiple times"),

        Option("-H", "--header-fields",
               dest="header_fields", default='all',
               help="Header fields (comma separated) to be printed as well (if present)"),

        Option("-t", "--text",
               dest="text",
               help="Print output in a very nice-looking way"),

        Option("-j", "--json",
               dest="json",
               help="Print output in a json way"),

        Option("-y", "--yaml",
               dest="yaml",
               help="Print output in a yaml way"),
    ])

    return p


def diff_values(compare1, compare2):
    """Generically compares two values and, if different, returns both as a tuple"""
    if np.any(compare1 != compare2):
        return compare1, compare2
    elif type(compare1) != type(compare2):
        return compare1, compare2
    else:
        pass


def diff_header_fields(key, inputs):
    """Iterates over a single header field of multiple files"""
    diffs = []

    # for comparing more than 2 files at once
    if len(inputs) > 2:
        input_1 = inputs[0]
        key_1 = input_1[key]
        for input_2 in inputs[1:]:
                key_2 = input_2[key]

                if diff_values(key_1, key_2):
                    if key_1 not in diffs:
                        diffs.append(key_1)
                    diffs.append(key_2)

                elif len(diffs) != 0:
                    diffs.append(key_2)

    # for comparing 2 files
    else:
        input_1 = inputs[0]
        input_2 = inputs[1]

        key_1 = input_1[key]
        key_2 = input_2[key]

        if np.any(key_1 != key_2):
            diffs.append(key_1)
            diffs.append(key_2)
        elif type(key_1) != type(key_2):
            diffs.append(key_1)
            diffs.append(key_2)

    # fixing some erroneous outputs generated by the above
    # TODO: figure out a way to not have these erroneous outputs occur in the above loop
    for a in range(len(diffs)-1):
        for b in range(len(diffs)-1):
            try:
                if np.all(np.isnan(diffs[a])) and np.all(np.isnan(diffs[a+1])):
                    del diffs[a]
            except TypeError:
                pass

    if len(diffs) > 1:
        return diffs


def get_headers_diff(files, opts):

    header_list = [nib.load(f).header for f in files]

    if opts.header_fields:
        # signals "all fields"
        if opts.header_fields == 'all':
            # TODO: header fields might vary across file types, thus prior sensing would be needed
            header_fields = header_list[0].keys()
        else:
            header_fields = opts.header_fields.split(',')

        output = {}

        for f in header_fields:
            val = diff_header_fields(f, header_list)

            if val is not None:
                output[f] = val

        return output


def main():
    """NO DAYS OFF"""

    parser = get_opt_parser()
    (opts, files) = parser.parse_args()

    nibabel.cmdline.utils.verbose_level = opts.verbose

    assert len(files) >= 2, "Please enter at least two files"

    if nibabel.cmdline.utils.verbose_level < 3:
        # suppress nibabel format-compliance warnings
        nib.imageglobals.logger.level = 50

    diff = get_headers_diff(files, opts)

    if opts.text:
        print(diff)

    if opts.json:
        if isinstance(diff, binary_type):
            print(json_tricks.dumps(diff.decode("utf-8")))
        else:
            print(json_tricks.dumps(diff))
