ci:
  autoupdate_schedule: monthly
  autoupdate_commit_message: 'chore: update pre-commit hooks'
  autofix_prs: false
  skip:
    - typecheck

exclude: ".*/data/.*"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.3
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  # Use uv run so we can use uv pinning
  - repo: local
    hooks:
      - id: typecheck
        name: Typecheck
        language: python
        entry: uv run --active --no-dev --group=typecheck mypy nibabel
        pass_filenames: false
        additional_dependencies: [uv]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
