name: nibabel-dev
channels:
  - defaults
dependencies:
  - python>=3.7
  - pip>=19.3
  
  # setup
  - wheel
  - setuptools>=30.3.0

  # requirements
  - numpy>=1.12

  # doc requirements
  - sphinx
  - numpydoc
  - matplotlib>=1.3

  # testing
  - nose>=0.11
  - mock

  # code style
  - flake8
  - pep8-naming
  - pip:
    # doc requirements
    - texext

    # code style
    - flake8-docstrings
