# Makefile NiBabel under Windows using a standard Python distribution

installer: 
	# now the installer
	python setup.py bdist_wininst

#
# Cleaning
#

clean:
	-rmdir /S /Q
	-del /S *.a *.o *.gch *.pyd

#
# Testing
#

unittest:
	@set PYTHONPATH=$(CURDIR) & nosetests nibabel


#
# Trailer
#

.PHONY: all
