# Minimalistic makefile for libsvm
LIB=libniftiio.a libznz.a
MISC=nifti1_io.c znzlib.c

LIBFLAGS=
CFLAGS=-Wall -O2 -I. -DHAVE_ZLIB -DWIN32

all: $(LIB)

.c.o:
	gcc $(CFLAGS) $(LIBFLAGS) -c $^

libniftiio.a: nifti1_io.o
	ar cur $@ $^

libznz.a: znzlib.o
	ar cur $@ $^

clean:
	-del $(LIB) $(MISC:.c=.o)
