# Minimalistic makefile for libnifti
LIB=libniftiio.a libznz.a
MISC=nifti1_io.c znzlib.c

LIBFLAGS=
CFLAGS=-Wall -O2 -I. -DHAVE_ZLIB -DWIN32

TDIR=..\..\build\nifticlibs

all: prep $(LIB)

prep:
	-mkdir ..\..\build
	-mkdir $(TDIR)

.c.o:
	gcc $(CFLAGS) $(LIBFLAGS) -c $^ -o $(TDIR)\$(^:.c=.o)

libniftiio.a: nifti1_io.o
	ar curs $(TDIR)\$@ $(TDIR)\$^

libznz.a: znzlib.o
	ar curs $(TDIR)\$@ $(TDIR)\$^

clean:
	-rmdir $(TDIR)
	-del *-stamp
