#!/usr/bin/env python
"""nibabel release build script.
"""
from toollib import *

# Get main nibabel dir, this will raise if it doesn't pass some checks
nibdir = get_nibdir()
cd(nibdir)

# Load release info
execfile(pjoin('nibabel','info.py'))

# Check that everything compiles
compile_tree()

# Cleanup
for d in ['build','dist',pjoin('docs','build'),pjoin('docs','dist')]:
    if os.path.isdir(d):
        remove_tree(d)

# Build source and binary distros
c('./setup.py sdist --formats=gztar,zip')

# Build eggs
#c('python2.5 ./setupegg.py bdist_egg')
c('python2.6 ./setupegg.py bdist_egg')
