#!/usr/bin/env python
"""nibabel release build script.
"""
from toollib import *

# Get main nibabel dir, this will raise if it doesn't pass some checks
nibdir = get_nibdir()
cd(nibdir)

# Load release info
execfile(pjoin('nibabel','info.py'))

# Check that everything compiles
compile_tree()

# Cleanup
for d in ['build','dist',pjoin('docs','build'),pjoin('docs','dist')]:
    if os.path.isdir(d):
        remove_tree(d)

# Build source and binary distros
c('./setup.py sdist --formats=gztar,zip')

# Build eggs
for version in ['2.5', '2.6', '2.7']:
    cmd='python'+version+' ./setup_egg.py bdist_egg'
    stat = os.system(cmd)
