name: Build documentation

on:
  push:
    branches:
      - ci/build-docs
    tags:
      - '*'
  # Allow job to be triggered manually from GitHub interface
  workflow_dispatch:

defaults:
  run:
    shell: bash

# Force tox and pytest to use color
env:
  FORCE_COLOR: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-slim']
        python-version: ['3.14']

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: true
          enable-cache: false
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install tox
        run: uv tool install -v tox --with=tox-uv-bare
      - name: Setup tox environment
        run: tox run -vv --notest -e docs
      - name: Build docs
        run: tox -v --skip-pkg-install -e docs
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags'))
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
